### ISSUE TITLE
Merge "outline", "solid" etc 

### ISSUE THREAD

**Issue by finnsnape** [janosh/svicons#11]
I was wondering if you would consider merging the different icon styles into one package per icon pack. For example you would do:
```html
<script lang="ts">
import Trophy from '@svicons/ionicons/trophy.svelte';
</script>

<Trophy style="solid" width="38px" height="38px" color="black"/>
<Trophy style="outline" width="20px" height="20px" color="red"/>
```

**Comment by janosh** [comment]
Thanks for the suggestion. It would add significant complexity and break with the goal of being a one-to-one reproduction of the `styled-icons` project for the Svelte ecosystem. Since the icon explorer for this project isn't finished yet, you could no longer use the one at styled-icons.dev as a replacement. For those reasons, I think it's better to leave solid/outline/two-tone as separate packages.
